### ISSUE TITLE
Hi, Do you have any first time contribution issues

### ISSUE THREAD

**Issue by M-ZubairAhmed** [johnkorzhuk/grabient#3]
First of all awesome work with the tool, i have utilized it in one of my projects. I wanted to know if you have any first time tagged issues. If yes i would love to get started to be my first contribution to open source.

**Comment by johnkorzhuk** [comment]
@M-ZubairAhmed Thanks! That's awesome to hear, I'm glad this tool is proving to be useful for people. I'm not sure what is you're asking for, I myself am pretty new to making contributions. So if you have any resources you can share with me that'll help make it easier for people to contribute, I'd love to know.

**Comment by johnkorzhuk** [comment]
I'm closing this issue for now. Please feel free to reopen it if you have any more questions or want to get back to me about your original inquiry.
