### ISSUE TITLE
Adding proptypes

### ISSUE THREAD

**Issue by M-ZubairAhmed** [johnkorzhuk/grabient#4]
I have seen that you have mentioned 
>TODO add proptypes with flow
in read me. Is it something you are willing to work on or you need help with that. I can help with that if you are up for it

**Comment by johnkorzhuk** [comment]
It was placed there as a reminder to myself. I just haven't got the chance to get around to it. Feel free to submit a pull request. I have plans to add a small backend or firebase to the app for user-submitted gradients and upvotes/downvotes. When I do that, I'll make any necessary changes to conform to Airbnb's eslint rules.

**Comment by Booligoosh** [comment]
@johnkorzhuk Is there any way to do PRs with new gradients without installing Sketch? If so how?

Thanks btw, really beautiful site :)

**Comment by johnkorzhuk** [comment]
@Booligoosh Thanks for the kind words. Last weekend I've added Firebase as a backend and authentication service. This update will allow users to sign in and submit their own gradients to be displayed on the front page of Grabient. Stay tuned for that :)

**Comment by M-ZubairAhmed** [comment]
@johnkorzhuk do you still want me to go ahead with this issue
